#!/usr/bin/env node
/*
 * Generate a release dogfood sign-off: sample N figures (default 25) and write
 * DOGFOOD.md — a checklist a human walks through in the BUILT artifact
 * (dist/pantheon-registry.html#/browse/<id>), confirming powers, items, domains,
 * and native-script rendering actually display. The automated counterpart lives
 * in test/dogfood.test.cjs; this is the human-eyes pass.
 *
 * Sampling is seeded (default: today's UTC date) so a run is reproducible and
 * auditable, and each release samples a fresh spread. Override:
 *   node scripts/dogfood-sample.cjs [N] [seed]
 */
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const N = parseInt(process.argv[2], 10) || 25;
const SEED_STR = process.argv[3] || new Date().toISOString().slice(0, 10);
const ROOT = path.join(__dirname, '..');

// Deterministic PRNG (mulberry32) seeded from the date string.
function seedFrom(s) { let h = 1779033703 ^ s.length; for (let i = 0; i < s.length; i++) { h = Math.imul(h ^ s.charCodeAt(i), 3432918353); h = (h << 13) | (h >>> 19); } return h >>> 0; }
function mulberry32(a) { return function () { a |= 0; a = (a + 0x6D2B79F5) | 0; let t = Math.imul(a ^ (a >>> 15), 1 | a); t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t; return ((t ^ (t >>> 14)) >>> 0) / 4294967296; }; }

// Load the seed exactly as the app does.
const store = new Map();
const ctx = { window: { dispatchEvent: () => true }, localStorage: { getItem: (k) => store.has(k) ? store.get(k) : null, setItem: (k, v) => store.set(k, String(v)), removeItem: (k) => store.delete(k) }, console: { log() {}, warn() {}, error() {}, info() {} }, CustomEvent: class { constructor(t, o) { Object.assign(this, { type: t }, o || {}); } } };
ctx.globalThis = ctx; vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(ROOT, 'app', 'data.js'), 'utf8'), ctx, { filename: 'data.js' });
const people = JSON.parse(ctx.localStorage.getItem('pantheon_registry_v8'));

// Seeded shuffle of all ids, then take N.
const rnd = mulberry32(seedFrom(SEED_STR));
const ids = Object.keys(people).sort();
for (let i = ids.length - 1; i > 0; i--) { const j = Math.floor(rnd() * (i + 1)); [ids[i], ids[j]] = [ids[j], ids[i]]; }
const sample = ids.slice(0, N).sort();

const nm = (p) => (p.name && (p.name.primary || p.name)) || (p.names && p.names[0] && (p.names[0].value || p.names[0].primary)) || '(unnamed)';
const terms = (arr) => (arr || []).map((e) => e.term && e.term.value).filter(Boolean).slice(0, 3).join(', ');

let md = `# Dogfood sign-off\n\n`;
md += `Generated by \`scripts/dogfood-sample.cjs\` · sample size **${N}** · seed \`${SEED_STR}\` · corpus ${ids.length} figures.\n\n`;
md += `Open each figure in the **built artifact** — \`dist/pantheon-registry.html#/browse/<id>\` — and confirm the four boxes render correctly (powers as verb-phrases with native terms, items/material culture, domains with native terms, and non-Latin scripts displaying — not mojibake). Tick the row when verified.\n\n`;
md += `| # | figure | tradition | powers / items / domains | sample native terms | ✓ |\n`;
md += `|---|--------|-----------|--------------------------|---------------------|---|\n`;
sample.forEach((id, i) => {
  const p = people[id];
  const counts = `${(p.faculties || []).length} / ${(p.materialCulture || []).length} / ${(p.domains || []).length}`;
  const t = [terms(p.faculties), terms(p.domains)].filter(Boolean).join(' · ') || '—';
  md += `| ${i + 1} | [${nm(p)}](dist/pantheon-registry.html#/browse/${encodeURIComponent(id)}) \`${id}\` | ${p.primaryTradition || p.tradition || '—'} | ${counts} | ${t} | ☐ |\n`;
});
md += `\n## Reviewer sign-off\n\n`;
md += `- [ ] All ${N} figures open in the built artifact with no console errors\n`;
md += `- [ ] Powers read as plain-English verb phrases with the native term alongside\n`;
md += `- [ ] Items / material culture render with roles and native terms\n`;
md += `- [ ] Domains render with native terms; non-Latin scripts display correctly\n`;
md += `- [ ] No fabricated / unattested content spotted\n\n`;
md += `Reviewer: __________________  Date: __________  Release/commit: __________\n`;

fs.writeFileSync(path.join(ROOT, 'DOGFOOD.md'), md);
console.log(`wrote DOGFOOD.md — ${N} sampled figures (seed ${SEED_STR})`);
